version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: logistica_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: logistica_grupo12
      POSTGRES_USER: logistica_user
      POSTGRES_PASSWORD: logistica_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5632:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
