version: '3.8'

services:
  # ===================================
  # POSTGRESQL - Base de Datos Principal
  # ===================================
  postgres:
    image: postgres:15-alpine
    container_name: logistica_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: logistica_grupo12
      POSTGRES_USER: logistica_user
      POSTGRES_PASSWORD: logistica_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistica_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logistica_user -d logistica_grupo12"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===================================
  # REDIS - Cache y Sesiones
  # ===================================
  redis:
    image: redis:7-alpine
    container_name: logistica_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - logistica_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # ===================================
  # PGADMIN - Administración de BD (Opcional)
  # ===================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: logistica_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@logistica.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - logistica_network
    depends_on:
      - postgres
    profiles:
      - tools  # Solo se levanta con: docker-compose --profile tools up

# ===================================
# NETWORKS
# ===================================
networks:
  logistica_network:
    driver: bridge
    name: logistica_network

# ===================================
# VOLUMES
# ===================================
volumes:
  postgres_data:
    name: logistica_postgres_data
  redis_data:
    name: logistica_redis_data
  pgadmin_data:
    name: logistica_pgadmin_data