version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: logistica-postgres
    environment:
      POSTGRES_DB: logistica_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistica-network

  redis:
    image: redis:7-alpine
    container_name: logistica-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - logistica-network

volumes:
  postgres_data:
  redis_data:

networks:
  logistica-network:
    driver: bridge
